 const values = {
  items: [
    {
    id: 1,
    name: 'Noize MC',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere efficitur vestibulum. Fusce ac justo diam. Duis eget erat eu mi tristique pretium. Donec ullamcorper blandit velit, eget feugiat nibh bibendum quis. Vestibulum tellus justo, feugiat vitae sapien id, accumsan mattis nibh. Suspendisse orci dolor, imperdiet nec ultricies vitae, aliquam eu nulla. Integer varius eros aliquam, pulvinar ante ac, pretium nisi. Duis congue tempus massa, eu sagittis augue dignissim eu. Phasellus euismod maximus tincidunt. Cras sed lectus eu libero porta congue vel vel lorem. Suspendisse imperdiet purus eget blandit luctus. Phasellus pharetra eu orci eget lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus lobortis metus turpis, eu congue dui cursus et. Nullam rutrum tristique consequat. Curabitur sodales nibh dui, ac dapibus urna sodales non. Suspendisse potenti. Morbi ac diam dolor. Cras accumsan eros rutrum, ultricies ex at, dapibus neque. Aenean sed fermentum nunc. Curabitur pellentesque ac purus non ultrices. Suspendisse consectetur in nulla eu eleifend. Donec consectetur magna id tellus porta maximus. Maecenas ac ante et risus convallis vestibulum non in nunc. Phasellus pulvinar libero in nisl pharetra, a dapibus ligula semper. Phasellus posuere eros at faucibus rutrum. Vivamus commodo, lacus sed gravida semper, urna est pulvinar mauris, id aliquet lectus magna eu tortor. Donec mollis dolor risus, at placerat augue elementum ut. Nam augue massa, mollis at vehicula nec, pharetra at tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut sed faucibus lorem. Suspendisse nec nunc in ipsum dictum gravida. Nunc elementum iaculis purus, vel feugiat libero euismod sed. Nulla at eros pharetra, laoreet velit non, elementum magna. Sed euismod orci sit amet tellus faucibus, vel fringilla odio vehicula. Fusce lectus massa, volutpat nec turpis in, egestas condimentum ante. Maecenas id libero et sem pretium rutrum. Aenean porta magna eget tellus dapibus tincidunt non id lorem. Donec accumsan sagittis ante, commodo semper lorem finibus a. Nam sit amet lorem tincidunt, ultrices ex lobortis, tempor leo. Donec pretium elit vel dui lacinia condimentum. Cras suscipit, urna eget interdum tincidunt, sapien nisi rhoncus elit, lacinia tempor diam enim sit amet eros. Sed facilisis vulputate leo, sed faucibus odio suscipit nec. Duis eget diam vitae tortor malesuada venenatis. Donec libero sapien, porta nec nibh eu, pretium viverra ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    urlImage: 'http://musicafisha.ru/sites/default/files/noize-mc-2012-spb2.jpg',
    urlVideo: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4'
  },{
    id: 2,
    name: 'Anacondaz',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere efficitur vestibulum. Fusce ac justo diam. Duis eget erat eu mi tristique pretium. Donec ullamcorper blandit velit, eget feugiat nibh bibendum quis. Vestibulum tellus justo, feugiat vitae sapien id, accumsan mattis nibh. Suspendisse orci dolor, imperdiet nec ultricies vitae, aliquam eu nulla. Integer varius eros aliquam, pulvinar ante ac, pretium nisi. Duis congue tempus massa, eu sagittis augue dignissim eu. Phasellus euismod maximus tincidunt. Cras sed lectus eu libero porta congue vel vel lorem. Suspendisse imperdiet purus eget blandit luctus. Phasellus pharetra eu orci eget lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus lobortis metus turpis, eu congue dui cursus et. Nullam rutrum tristique consequat. Curabitur sodales nibh dui, ac dapibus urna sodales non. Suspendisse potenti. Morbi ac diam dolor. Cras accumsan eros rutrum, ultricies ex at, dapibus neque. Aenean sed fermentum nunc. Curabitur pellentesque ac purus non ultrices. Suspendisse consectetur in nulla eu eleifend. Donec consectetur magna id tellus porta maximus. Maecenas ac ante et risus convallis vestibulum non in nunc. Phasellus pulvinar libero in nisl pharetra, a dapibus ligula semper. Phasellus posuere eros at faucibus rutrum. Vivamus commodo, lacus sed gravida semper, urna est pulvinar mauris, id aliquet lectus magna eu tortor. Donec mollis dolor risus, at placerat augue elementum ut. Nam augue massa, mollis at vehicula nec, pharetra at tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut sed faucibus lorem. Suspendisse nec nunc in ipsum dictum gravida. Nunc elementum iaculis purus, vel feugiat libero euismod sed. Nulla at eros pharetra, laoreet velit non, elementum magna. Sed euismod orci sit amet tellus faucibus, vel fringilla odio vehicula. Fusce lectus massa, volutpat nec turpis in, egestas condimentum ante. Maecenas id libero et sem pretium rutrum. Aenean porta magna eget tellus dapibus tincidunt non id lorem. Donec accumsan sagittis ante, commodo semper lorem finibus a. Nam sit amet lorem tincidunt, ultrices ex lobortis, tempor leo. Donec pretium elit vel dui lacinia condimentum. Cras suscipit, urna eget interdum tincidunt, sapien nisi rhoncus elit, lacinia tempor diam enim sit amet eros. Sed facilisis vulputate leo, sed faucibus odio suscipit nec. Duis eget diam vitae tortor malesuada venenatis. Donec libero sapien, porta nec nibh eu, pretium viverra ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    urlImage: 'https://www.yaidu.ru/stageaction/anacondaz/upload/cover_s0.jpg?1443110452',
    urlVideo: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4'
  },{
    id: 3,
    name: 'Oxxxymiron',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere efficitur vestibulum. Fusce ac justo diam. Duis eget erat eu mi tristique pretium. Donec ullamcorper blandit velit, eget feugiat nibh bibendum quis. Vestibulum tellus justo, feugiat vitae sapien id, accumsan mattis nibh. Suspendisse orci dolor, imperdiet nec ultricies vitae, aliquam eu nulla. Integer varius eros aliquam, pulvinar ante ac, pretium nisi. Duis congue tempus massa, eu sagittis augue dignissim eu. Phasellus euismod maximus tincidunt. Cras sed lectus eu libero porta congue vel vel lorem. Suspendisse imperdiet purus eget blandit luctus. Phasellus pharetra eu orci eget lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus lobortis metus turpis, eu congue dui cursus et. Nullam rutrum tristique consequat. Curabitur sodales nibh dui, ac dapibus urna sodales non. Suspendisse potenti. Morbi ac diam dolor. Cras accumsan eros rutrum, ultricies ex at, dapibus neque. Aenean sed fermentum nunc. Curabitur pellentesque ac purus non ultrices. Suspendisse consectetur in nulla eu eleifend. Donec consectetur magna id tellus porta maximus. Maecenas ac ante et risus convallis vestibulum non in nunc. Phasellus pulvinar libero in nisl pharetra, a dapibus ligula semper. Phasellus posuere eros at faucibus rutrum. Vivamus commodo, lacus sed gravida semper, urna est pulvinar mauris, id aliquet lectus magna eu tortor. Donec mollis dolor risus, at placerat augue elementum ut. Nam augue massa, mollis at vehicula nec, pharetra at tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut sed faucibus lorem. Suspendisse nec nunc in ipsum dictum gravida. Nunc elementum iaculis purus, vel feugiat libero euismod sed. Nulla at eros pharetra, laoreet velit non, elementum magna. Sed euismod orci sit amet tellus faucibus, vel fringilla odio vehicula. Fusce lectus massa, volutpat nec turpis in, egestas condimentum ante. Maecenas id libero et sem pretium rutrum. Aenean porta magna eget tellus dapibus tincidunt non id lorem. Donec accumsan sagittis ante, commodo semper lorem finibus a. Nam sit amet lorem tincidunt, ultrices ex lobortis, tempor leo. Donec pretium elit vel dui lacinia condimentum. Cras suscipit, urna eget interdum tincidunt, sapien nisi rhoncus elit, lacinia tempor diam enim sit amet eros. Sed facilisis vulputate leo, sed faucibus odio suscipit nec. Duis eget diam vitae tortor malesuada venenatis. Donec libero sapien, porta nec nibh eu, pretium viverra ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    urlImage: 'http://img.odessa1.com/images/events/326x464/m2-14967-1.jpg',
    urlVideo: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4'
  }]
};

export default values;
